6-38
(a)
ALTER TABLE STUDENT
ADD COLUMN Class VARCHAR(10);
(b)
DROP TABLE 	REGITRATION ;

6-39
(a)
INSERT INTO STUDENT(StudentID,StudentName)
VALUES('65798 ','Lopez');
(b)
DELETE FROM STUDENT
WHERE StudentName='Lopez';
(c)
UPDATE COURSE
SET CourseName 'Introduction to Relational Databases'  WHERE CourseID= 'ISM 4212' ;

6-40
(a)
SELECT StudentName FROM STUDENT
WHERE StudentID < 50000;
(b)
SELECT FacultyName FROM FACULTY
WHERE FacultyID = 4756;
(c)
SELECT MIN(SectionNo) FROM SECTION
WHERE Semester = 'I-2015';

6-41
(a)
SELECT COUNT(StudentID) FROM REGITRATION
WHERE SectionNo=2714;
(b)
SELECT A1.FacultyID FacultyID,A2.CourseName CourseName,A3.DataQualified DataQualified
FROM FACULTY A1,COURSE A2,QUALIFIED A3
WHERE A3.DataQualified LIKE = '*/2008' AND A3.CourseID=A2.CourseID AND A3.FacultyID=A1.FacultyID;

6-43
(a)
SELECT DISTINCT COURSE.CourseName
FROM COURSE WHERE COURSE.CourseID=SECTION.CourseID;
(b)SELECT StudentName FROM STUDENT
ORDER by StudentName;

6-45
SELECT COUNT(TutorID) FROM TUTOR
WHERE Status='Temp Stop';

6-46
SELECT AVG(Read) FROM STUDENT;
SELECT MIN(Read) FROM STUDENT;
SELECT MAX(Read) FROM STUDENT;

6-47
SELECT TutorID FROM MATCH HISTORY
WHERE EndDATE =NULL
GROUP BY TutorID
HAVING COUNT(MatchId)>=2 

6-48
SELECT TUTOR.TutorID FROM TUTOR
WHERE TUTOR.TutorID not in 
(SELECT MATCH HISTORY.TutorID FROM MATCH HISTORY;);







