-- SQL Dump of 資料庫1.accdb
-- generated by MDB Viewer 2.2.6
-- optimized for MySQL

SET NAMES 'UTF8';



DROP TABLE IF EXISTS `借出紀錄`;

CREATE TABLE `借出紀錄` (
    `借出單號` INTEGER PRIMARY KEY,
    `預約單號` INTEGER,
    `腳踏車編號` INTEGER,
    `實際取車時間` DATETIME
) CHARACTER SET 'UTF8';




DROP TABLE IF EXISTS `學生`;

CREATE TABLE `學生` (
    `學號` INTEGER PRIMARY KEY,
    `姓名` VARCHAR(255),
    `電話` INTEGER,
    `性別` VARCHAR(255)
) CHARACTER SET 'UTF8';




DROP TABLE IF EXISTS `時段`;

CREATE TABLE `時段` (
    `時段` VARCHAR(255) PRIMARY KEY,
    `價格` DOUBLE
) CHARACTER SET 'UTF8';




DROP TABLE IF EXISTS `歸還紀錄`;

CREATE TABLE `歸還紀錄` (
    `歸還單號` INTEGER PRIMARY KEY,
    `借出單號` INTEGER,
    `歸還站` VARCHAR(255),
    `歸還時間` DATETIME
) CHARACTER SET 'UTF8';




DROP TABLE IF EXISTS `租借站`;

CREATE TABLE `租借站` (
    `中文站名` VARCHAR(255) PRIMARY KEY,
    `地點` VARCHAR(255),
	`經度` DOUBLE,
    `緯度` DOUBLE,
    `目前車輛` INTEGER,
    `可用空格` INTEGER
) CHARACTER SET 'UTF8';




DROP TABLE IF EXISTS `腳踏車`;

CREATE TABLE `腳踏車` (
    `腳踏車編號` INTEGER PRIMARY KEY,
    `廠牌` VARCHAR(255),
    `規格` VARCHAR(255),
    `車況` VARCHAR(255)
) CHARACTER SET 'UTF8';




DROP TABLE IF EXISTS `預約單`;

CREATE TABLE `預約單` (
    `預約單號` INTEGER PRIMARY KEY,
    `學號` INTEGER,
    `時段` VARCHAR(255),
    `站名` VARCHAR(255),
    `欲租車日期` DATETIME,
    `數量` INTEGER,
    `預約日` DATETIME
) CHARACTER SET 'UTF8';

LOAD DATA LOCAL INFILE 'ticket_list'
INTO TABLE `預約單`



